#!/usr/bin/env bash

keys=$(sudo showkey | grep keycode -c)

if [[ $keys == "0" ]]; then
    xdotool key Super_L+alt+o
    xdotool key Super_L+m
    xdotool key Super_L+w
    notify-send "idle start detected"
fi
