#!/usr/bin/env bash

keys=$(sudo showkey | grep keycode -c)
keys+=$(sudo showkey | grep keycode -c)

if [[ $keys == "00" ]]; then
    xdotool key Super_L+alt+o
    xdotool key Super_L+m
    xdotool key Super_L+w
    notify-send -u critical "idle start detected"
fi
