#!/bin/sh

# A rofi -dmenu wrapper script for system functions.

cmds="\
 shutdown	shutdown -h now
 reboot	reboot
 lock		slock
 logout	xdotool key Super_L+alt+control+q
 cancel"

choice="$(echo "$cmds" | cut -d'	' -f 1 | rofi -dmenu -l 5)" || exit 1

eval "$(echo "$cmds" | grep "^$choice	" | cut -d '	' -f2-)"
