#!/bin/sh

while true
do
    read -r -p "Install Nerd Fonts? [Y/n] " nerdfont
    case "$nerdfont" in
        [yY][eE][sS]|[yY]|"")
            echo "installing font..."
            yay --nocleanmenu --nodiffmenu --noeditmenu --removemake -S nerd-fonts-dejavu-complete ttf-joypixels
            if [[ $? != 0 ]]; then echo "error installing font"; exit 1; fi
            break
            ;;
        [nN][oO]|[nN]) break ;;
        *) echo "Invalid Option" ;;
    esac
done

while true
do
    read -r -p "Install Suckless Desktop? [Y/n] " desktop
    case "$desktop" in
        [yY][eE][sS]|[yY]|"")
            echo "installing desktop enviroment..."
            sudo pacman -S lightdm lightdm-slick-greeter --noconfirm
            if [[ $? != 0 ]]; then echo "error installing lightdm"; exit 1; fi
            sudo systemctl enable lightdm.service
            if [[ $? != 0 ]]; then echo "error enableling lightdm in systemctl"; exit 1; fi

            sudo pacman -S dunst libnotify xorg-appres jgmenu rofi --noconfirm
            if [[ $? != 0 ]]; then echo "error installing dunst"; exit 1; fi
            yay --nocleanmenu --nodiffmenu --noeditmenu --removemake -S picom-animations-git
            if [[ $? != 0 ]]; then echo "error installing picom"; exit 1; fi

            sudo pacman -S imlib2 libxcb libxinerama --noconfirm
            if [[ $? != 0 ]]; then echo "error installing dependencies"; exit 1; fi

            cd $HOME
            mkdir .suckless
            if [[ $? != 0 ]]; then echo "error making suckless directory"; exit 1; fi
            cd .suckless

            clear=0
            git clone https://github.com/bakkeby/dwm-flexipatch.git dwm; clear=$(($clear + $?))
            git clone https://github.com/bakkeby/st-flexipatch.git st ; clear=$(($clear + $?))
            # git clone https://github.com/bakkeby/dmenu-flexipatch.git dmenu ; clear=$(($clear + $?))
            git clone https://github.com/bakkeby/slock-flexipatch.git slock ; clear=$(($clear + $?))
            # git clone https://git.suckless.org/scroll ; clear=$(($clear + $?))
            git clone https://github.com/torrinfail/dwmblocks.git ; clear=$(($clear + $?))
            if [[ $clear != 0 ]]; then echo "error downloading source code"; exit 1; fi

            cd dwmblocks
            curl https://dwm.suckless.org/patches/statuscmd/dwmblocks-statuscmd-20210402-96cbb45.diff | patch -p1
            if [[ $? != 0 ]]; then echo "error patching dwmblocks"; exit 1; fi
            cd ..

            if [[ -d $HOME/.config/suckless/ ]]; then
                for dir in $(ls $HOME/.config/suckless/); do
                    if [[ -d "$dir" ]]; then
                        ln $HOME/.config/suckless/$dir/*.h $dir/
                        if [[ $? != 0 ]]; then echo "error creating links"; exit 1; fi
                        if [[ -f "$HOME/.config/suckless/$dir/config.mk" ]]; then
                            mv $dir/config.mk config.mk.$dir.backup
                            ln $HOME/.config/suckless/$dir/config.mk $dir
                            if [[ $? != 0 ]]; then echo "error replacing config.mk files"; exit 1; fi
                        fi
                    fi
                done
            fi

            cd dwm/ && sudo make clean install ; clear=$(($clear + $?))
            cd ../dwmblocks/ && sudo make clean install ; clear=$(($clear + $?))
            # cd ../dmenu/ && sudo make clean install ; clear=$(($clear + $?))
            cd ../st/ && sudo make clean install ; clear=$(($clear + $?))
            # cd ../scroll/ && sudo make clean install ; clear=$(($clear + $?))
            cd ../slock/ && sudo make clean install ; clear=$(($clear + $?))
            if [[ $clear != 0 ]]; then echo "error building the desktop"; exit 1; fi

            sudo mkdir /usr/share/xsessions/
            sudo cp $HOME/.config/suckless/dwm/dwm.desktop /usr/share/xsessions/
            if [[ $? != 0 ]]; then echo "error adding desktop image to xsession"; exit 1; fi

            sudo pacman -S autorandr --noconfirm

            break
            ;;
        [nN][oO]|[nN]) break ;;
        *) echo "Invalid Option" ;;
    esac
done

while true
do
    read -r -p "Install NeoVim? [Y/n] " neovim
    case "$neovim" in
        [yY][eE][sS]|[yY]|"")
            echo "installing neovim..."
            sudo pacman -S neovim xclip lua --noconfirm
            if [[ $? != 0 ]]; then echo "error installing neovim"; exit 1; fi
            break
            ;;
        [nN][oO]|[nN]) break ;;
        *) echo "Invalid Option" ;;
    esac
done

while true
do
    read -r -p "Install pywal and theming dependencies? [Y/n] " wal
    case "$wal" in
        [yY][eE][sS]|[yY]|"")
            echo "installing pywal..."
            sudo pacman -S python-pywal sxiv feh xdotool --noconfirm
            if [[ $? != 0 ]]; then echo "error installing pywal"; exit 1; fi
            yay --nocleanmenu --nodiffmenu --noeditmenu --removemake -S themix-theme-oomox-git themix-icons-numix-git
            break
            ;;
        [nN][oO]|[nN]) break ;;
        *) echo "Invalid Option" ;;
    esac
done

while true
do
    read -r -p "Install librewolf? [Y/n] " browser
    case "$browser" in
        [yY][eE][sS]|[yY]|"")
            echo "installing browser..."
            yay --nocleanmenu --nodiffmenu --noeditmenu --removemake -S librewolf-bin
            if [[ $? != 0 ]]; then echo "error installing the browser"; exit 1; fi
            break
            ;;
        [nN][oO]|[nN]) break ;;
        *) echo "Invalid Option" ;;
    esac
done

while true
do
    read -r -p "Install misc? [Y/n] " misc
    case "$misc" in
        [yY][eE][sS]|[yY]|"")
            echo "installing misc..."
            sudo pacman -S zathura zathura-djvu zathura-pdf-poppler zathura-ps --noconfirm
            sudo pacman -S bash-completion neofetch btop pamixer mpv udisks2 udiskie nemo nemo-fileroller xarchiver libqalculate lsd bat onboard keepassxc maim zbar networkmanager-openvpn glow --noconfirm
            if [[ $? != 0 ]]; then echo "error installing the browser"; exit 1; fi
            break
            ;;
        [nN][oO]|[nN]) break ;;
        *) echo "Invalid Option" ;;
    esac
done
