#!/bin/sh

#        -lf/nf/cf color
#            Defines the foreground color for low, normal and critical notifications respectively.
# 
#        -lb/nb/cb color
#            Defines the background color for low, normal and critical notifications respectively.
# 
#        -lfr/nfr/cfr color
#            Defines the frame color for low, normal and critical notifications respectively.

[ -f "$HOME/.cache/wal/colors.sh" ] && . "$HOME/.cache/wal/colors.sh"

pidof dunst && killall dunst

dunst -lf  "${color7:-#ffffff}" \
      -lb  "${color1:-#eeeeee}" \
      -lfr "${color7:-#dddddd}" \
      -nf  "${color7:-#cccccc}" \
      -nb  "${color1:-#bbbbbb}" \
      -nfr "${color7:-#aaaaaa}" \
      -cf  "${color5:-#999999}" \
      -cb  "${color0:-#888888}" \
      -cfr "${color5:-#777777}" > /dev/null 2>&1 &
