#!/bin/sh

clock=$(date '+%I')

case "$clock" in
	"00") icon="󱑖" ;;
	"01") icon="󱑋" ;;
	"02") icon="󱑌" ;;
	"03") icon="󱑍" ;;
	"04") icon="󱑎" ;;
	"05") icon="󱑏" ;;
	"06") icon="󱑐" ;;
	"07") icon="󱑑" ;;
	"08") icon="󱑒" ;;
	"09") icon="󱑓" ;;
	"10") icon="󱑔" ;;
	"11") icon="󱑕" ;;
	"12") icon="󱑖" ;;
esac

case $BUTTON in
    1) notify-send -i ' ' "$(cal)" ;;
	3) pkill -RTMIN+1 dwmblocks ;;
esac

date "+󰭦 %Y/%b/%d (%a) | $icon %H:%M"
