#!/bin/sh

# Show wifi 直 and percent strength or 睊 if none.
# Show  if connected to ethernet
# Show  if a vpn connection is active

case $BUTTON in
	1) st -e nmtui; pkill -RTMIN+4 dwmblocks ;;
	3) pkill -RTMIN+4 dwmblocks ;;
esac

case "$(cat /sys/class/net/w*/operstate 2>/dev/null)" in
	down) wifiicon="睊 " ;;
	up) wifiicon="直 $(awk '/^\s*w/ { print int($3 * 100 / 70) }' /proc/net/wireless)% " ;;
esac

printf "%s%s%s\n" "$wifiicon" "$(sed "s/down//;s/up/ /" /sys/class/net/e*/operstate 2>/dev/null)" "$(sed "s/.*/ /" /sys/class/net/tun*/operstate 2>/dev/null)"
