#!/usr/bin/env bash

case $BUTTON in
  1) change-layout ;;
	2) setxkbmap -option caps:escape; pkill -RTMIN+10 dwmblocks ;;
	3) onboard ;;
esac

echo "$(setxkbmap -query | grep layout | awk '{print $2}')"
