#!/bin/sh

# Displays number of upgradeable packages.
# For this to work, have a `pacman -Sy` command run in the background every so often
# When clicked, it will run an upgrade via pacman.
#
# Add the following text as a executable file in /etc/NetworkManager/dispatcher.d/sync-packages
#
# #!/usr/bin/env bash
#
# if [[ $2 == "up" ]]; then
#         yay -Sy
#         pkill -RTMIN+8 dwmblocks
# fi

case $BUTTON in
	1) setsid -f st -e sb-popupgrade ;;
	3) yay -Sy; pkill -RTMIN+8 dwmblocks ;;
esac

pacman -Qu | grep -Fcv "[ignored]" | sed "s/^/ /;s/^ 0$//g"
