#!/bin/sh

# Prints the current volume or 🔇 if muted.

case $BUTTON in
	1) pamixer --allow-boost -d 5 ;;
	2) pamixer -t ;;
	3) pamixer --allow-boost -i 5 ;;
esac

[ $(pamixer --get-mute) = true ] && echo 婢 && exit

vol="$(pamixer --get-volume)"

if [ "$vol" -gt "70" ]; then
	icon="墳"
elif [ "$vol" -lt "30" ]; then
	icon="奄"
else
	icon="奔"
fi

echo "$icon $vol%"

