#!/bin/sh

if [ -d "/home/user/.scripts" ] ;
    then PATH="$PATH:/home/user/.scripts/"
fi

wal -R &
xrbd -merge /home/user/.Xresources &

autorandr --change &

launchdunst &

# while true; do
    # Log stderror to a file 
    dwm 2> /home/user/dwm.log
    # No error logging
    #dwm >/dev/null 2>&1
# done
