#!/bin/bash
cwd=$(pwd)

sxiv -fto $HOME/.config/wallpapers/*.{jpg,JPG,gif,GIF,png,PNG} | xargs -r wal -i

xrdb -merge $HOME/.cache/wal/colors.Xresources

xdotool key Super_L+shift+F5

genzathurarc > $HOME/.config/zathura/zathurarc && cat $HOME/.config/zathura/conf >> $HOME/.config/zathura/zathurarc
launchdunst

$HOME/.local/bin/razer-cli -a

oomox-cli $HOME/.cache/wal/colors-oomox
/opt/oomox/plugins/icons_numix/change_color.sh -o oomox-colors-oomox ~/.cache/wal/colors-oomox

notify-send "Theme successfully changed"

cd $cwd
